EthanTech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index),
    path('home/', views.index, name='home'),
    path('add_to_cart/<int:product_id>', views.add_to_cart, name='add_to_cart'),
    path('basket/', views.basket, name='basket'),
    path('basket/remove-item/<int:basket_id>', views.basketRemove, name='basket_remove_item'),
    path('account/login', views.loginregister, name='login'),
    path('account/create-account', views.create_user, name='create_account'),
    path('account/attempt-login', views.attemptLogin, name='attempt_login'),
    path('logout/', views.logout_view, name='logout')
]

main/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

# Create your models here.


class ProductModel(models.Model):
    """A class to create products by creating a product model object.
    This class is an extension of the :class:`models.Model` class.
    """
    CATEGORY_CHOICES = [
    ('FANS_AND_CPU_COOLERS', 'Fans & CPU Coolers'),
    ('CASES_CHASSIS', 'Cases / Chassis'),
    ('LAPTOP_NOTEBOOK', 'Laptops / Notebooks'),
]
    STOCK_CHOICES = [
        ('IN_STOCK', 'In stock'),
        ('IN_STOCK_WITH_SUPPLIER', 'In stock with supplier'),
        ('OUT_OF_STOCK', 'Out of stock'),
    ]
    product_name = models.TextField()
    product_description = models.TextField()
    stock_status = models.CharField(max_length=25,choices=STOCK_CHOICES)
    price = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    sale_price = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    image_file = models.CharField(max_length=200)
    component_category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0])

    def __str__(self):
        return self.product_name

class BasketModel(models.Model):
    """A class to create a basket for the user by creating a basket model object.
    This class is an extension of the :class:`models.Model` class.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    product = models.ForeignKey(ProductModel, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

main/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import *
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.forms import AuthenticationForm

from .models import ProductModel, BasketModel

@login_required(login_url='main:login')
def add_to_cart(request, product_id):
    """This will add an item to your cart.
    :param HttpRequest request: The request handed to the function that houses all the data
    :param int product_id: The id of the product being added to the cart

    :returns: The link to redirect towards

    :rtype: HttpResponseRedirect
    """
    product = get_object_or_404(ProductModel, pk=product_id)
    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))
        basket_item,created = BasketModel.objects.get_or_create(user=request.user, product_id=product_id, quantity=1)
        if not created:
            basket_item.quantity += quantity
            basket_item.save()
        else:
            basket_item.quantity = quantity
            basket_item.save()
        return redirect('main:home')
    return redirect('main:home')

def loginregister(request):
    """Sends you to the login page
    :param HttpRequest request: The request handed to the function that houses all the data.

    :returns: The response with the page to go to.

    :rtype: HttpResponse
    """
    return render(request, 'login.html')

# Create your views here.
def index(request):
    """The landing page when entering the site
    :param HttpRequest request: The request handed to the function that houses all the data.

    :returns: The response with the page to go to.

    :rtype: HttpResponse
    """
    products = ProductModel.objects.all()
    categories = ProductModel.CATEGORY_CHOICES
    context = {
        'products' : products,
        'categories' : categories,
    }
    return render(request=request, template_name='index.html', context=context)

@login_required(login_url='main:login')
def basket(request):
    """The entrypoint for seeing your basket.
    :param HttpRequest request: The request handed to the function that houses all the data.

    :returns: The response with the page to go to.

    :rtype: HttpResponse
    """
    user = request.user
    basket_items = BasketModel.objects.filter(user=user)
    context = {'basket_items': basket_items}
    return render(request, 'basket.html', context)

def basketRemove(request, basket_id):
    """This will remove an item to your cart.
    :param HttpRequest request: The request handed to the function that houses all the data
    :param int product_id: The id of the product being removed from the cart

    :returns: The link to redirect towards

    :rtype: HttpResponseRedirect
    """
    basket_item = get_object_or_404(BasketModel, id=basket_id, user=request.user)
    basket_item.delete()
    return redirect('main:basket')

def logout_view(request):
    """This will log you out of your current account.
    :param HttpRequest request: The request handed to the function that houses all the data

    :returns: The link to redirect towards

    :rtype: HttpResponseRedirect
    """
    logout(request)
    return redirect('main:home')

def create_user(request):
    """This will create an account.
    :param HttpRequest request: The request handed to the function that houses all the data

    :returns: The link to redirect towards

    :rtype: HttpResponseRedirect
    """
    firstName = request.POST['firstname']
    username = request.POST['username']
    password = request.POST['password']
    if User.objects.filter(username=username).exists():
        return redirect('main:login')
    user = User.objects.create_user(username=username, password=password, email=None, **{'first_name': firstName})
    user.save()
    return redirect('main:login')


def attemptLogin(request):
    """This will verify the given account details to an existing account.
    :param HttpRequest request: The request handed to the function that houses all the data

    :returns: The link to redirect towards

    :rtype: str
    """
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
        reverse('user_auth:login')
        )
    else:
        login(request, user)
        return HttpResponseRedirect(
        #reverse('user_auth:show_user')
        reverse('main:home')
        )

main/templates/basket.html
{% extends 'home.html' %}
{% block content %}
{% load static %}
<style>
    .basket-product-details{
        display: flex;
        list-style-type: none;
        padding: 0;
        margin: 0;
    }
    .basket-product-details li{
        margin-right: 10px;
    }
    .basket-product{
        margin-top: 10px;
        margin-bottom: 10px;
        display: flex;
        flex-direction: row;
        border-bottom: 1px solid rgba(171, 171, 171,0.5);
    }
    .title-description{
        display: flex;
        justify-content: space-evenly;
        flex-direction: column;
    }
    .image-container{
        height: 100px;
        width: 100px;
        margin-right: 10px;
    }

    .image-container img{
        height: 100%;
    }
    .input-quantity{
        width: 50px;
    }

    li form{
        font-size: 0.8em;
        width: 80px;
    }

    li form a{
        text-decoration: underline;
        color: black
    }
    li form a:hover{
        text-decoration: none;
        color: black
    }
</style>

{% for product in basket_items %}
<div class="container basket-product" id="basket-item-{{product.pk}}">
    <ul class="basket-product-details">
        <li class="image-container">
            <img src="{% static product.product.image_file|join:'' %}">
        </li>
        <li class="title-description" >
            <h4>{{ product.product.product_name }}</h4>
            <br>
            <h6>Basket ID: {{ product.pk }}</h6>
            <p>{{ product.product.product_description }}</p>
        </li>
        <li class="price-box">
            {% if product.product.sale_price > 0 %}
                <p class="original-price" style="font-size: 1em; text-decoration: line-through; color: rgb(171, 171, 171);">
                    R{{ product.product.price }}
                </p>
                <p class="sale-price" style="font-size: 1.5em; font-weight: 700; transform: translateY(-80%);">
                    R{{ product.product.sale_price }}
                </p>
                <input type="number" class="input-quantity" value="{{ product.quantity }}">
            {% else %}
                <p class="original-price" style="font-size: 1.5em; font-weight: 700;">
                    R{{ product.product.price }}
                </p>
                <input type="number" class="input-quantity" value="{{ product.quantity }}">
            {% endif %}
        </li>
        <li>
            <form class="remove-product" action="{% url 'main:basket_remove_item' product.pk %}">
                <a class="remove-basket-button" href="{% url 'main:basket_remove_item' product.pk %}">Remove item</a>
            </form>
        </li>
    </ul>
</div>
{% endfor %}
{% endblock %}

main/templates/home.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <title>Tech Store</title>
    <link rel="icon" href="{% static 'Images/catscree.JPG' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'CSS/home.css' %}">
  </head>
<body>
    <script src="{% static 'scroll.js' %}"></script>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav-bar">
        <!--Making the logo image and the company title appear on the navbar-->
        <img class="navbar-brand logo" src="{% static 'Images/non-copyright logo-only.jpg' %}" height="50">
        <a class="navbar-brand name" href="#" >Ethan's Tech</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!--Creating the button navigation options-->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:home' %}">Home</a>
                </li>
                <li class="nav-item" >
                    <a class="nav-link" href="#" onclick="scrollToElement('#contact-us')">Contact Us</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:basket' %}">Basket</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'main:login' %}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    
    <!--A nice peach coloured seperator between header and products-->
    <div style="background-color: rgb(249,204,157); height: 5px;">
        <span></span>
    </div>

    <!-- Shopping Items -->
    {% block content %}{% endblock %}

    <!--A nice peach coloured seperator between products and footer-->
    <div style="background-color: rgb(249,204,157); height: 5px;">
        <span style="padding-top: 50px;"></span>
    </div>

    <!--Footer-->
    <div>
        <footer class="footer bg-light" id="contact-us">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                    <form>
                        <div class="form-row">
                            <div class="form-group col-md-6" style="padding-top: 10px;">
                                <label for="inputName">Name</label>
                                <input type="text" class="form-control" id="inputName" placeholder="Enter your name">
                            </div>
                            <div class="form-group col-md-6" style="padding-top: 10px;">
                                <label for="inputEmail">Email</label>
                                <input type="email" class="form-control" id="inputEmail" placeholder="Enter your email address">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="inputMessage">Message</label>
                                <textarea class="form-control" id="inputMessage" rows="3" placeholder="Enter your message"></textarea>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                    <div class="col-md-4" style="padding-top: 10px;">
                        <h4>Contact Us</h4>
                        <p>123 Main St<br> Cape Town, South Africa<br> 061 372 7429</p>
                        <img src="{% static 'Images/non-copyright-logo.jpg' %}" width="150" style="padding-bottom: 5px;">
                    </div>
                </div>
            </div>
        </footer>
    </div>        
    <div id="bottom-page" style="background-color: rgb(248, 249, 250); padding-top: 5px;">
        <div class="container bottom-bar">
            <div class="row justify-content-center">
                <div class="col-md-2 mx-auto">
                    <a href="#" onclick="scrollToElement('#nav-bar')" style="color: rgba(0,0,0,.5); text-align: justify;" >Go To Top</a>
                </div> 
            </div>
        </div>
    </div>
    <div class="container credits">
        <a href="https://wootware.co.za/" target="_blank">Images and prices acquired from WootWare Computers.</a>
    </div>
</body>

main/templates/index.html
{% extends 'home.html' %}
{% block content %}
{% load static %}
<style>
    .category{
        background-color: rgb(242, 241, 241);
        margin-top: 0;
        padding-top: 5px;
        display: flex;
        justify-content: end;
        flex-direction: column;
    }

    .container.category:first-of-type{
        margin-top: 10px;
    }

    .category-title{
        margin-bottom: 12px;
        text-align: center;
    }

    .category ul{
        list-style: none;
        display: flex;
        justify-content: space-evenly;
        flex-direction: row;
        flex: 1;
    }
    .products-grid{
        background-color: white;
        border: 1px rgba(0,0,0,0.3) solid;
        border-radius: 5px;
        margin: 10px;
        padding: 0;
        height: 450px;
    }
    .product-image{
        height: 200px;
    }
    .availability{
        font-size: 1.1em;
        text-align: center;
        color: rgb(70, 131, 64);
    }
    .price-box{
        font-size: 1.3em;
        text-align: center;
        height: 32px;
        margin-bottom: 10px;
    }
        
    .product-name{
        align-self: center;
        position: relative;
        top:5px;
        text-align: center;
        height:59px;
        width:80%;
        margin-bottom: 8px;
    }

    .product-name{
        margin-bottom: 20px;
    }

    .product-name h3{
        font-size: 1em;
        margin: 0;
    }

    .price-box p{
        margin: 0;
    }

    .btn-add-to-cart{
        margin-bottom: 5px;
        background-color: white;
        border-radius: 1px;
        border: 3px solid rgb(245, 126, 75);
        color: rgb(245, 126, 75);
        font-size: 1em;
        font-weight: 700;
        transition: 0.3s ease;
    }

    .btn-add-to-cart:hover{
        color: white;
        border-radius: 1px;
        border: 3px solid rgb(245, 126, 75);
        background-color: rgb(245, 126, 75);
        font-size: 1em;
        font-weight: 700;
    }
    
    .products-grid li{
        width:33%;
        height: 100%;
        display: flex;
        justify-content: space-around;
        flex-direction: column;
        align-items: center;
        padding: 7px 10px 0px;
    }

</style>

<script src="{% static 'addtocard.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

{% for category in categories %}
    <div class="container category">
        <div class="block">
            <h2 class="category-title">
                {{ category.1 }} 
            </h2>
            <ul class="products-grid cols-5">
                {% for product in products %}
                    {% if product.component_category == category.0 %}
                        <li>
                            <div class="product-name">
                                <h3>
                                    {{ product.product_name }}
                                </h3>
                            </div>
                            <img class="product-image" src="{% static product.image_file|join:'' %}" alt="{{ product.product_name }}">
                            <div>
                                <div class="availability">
                                    {{ product.get_stock_status_display }}
                                </div>
                                <div class="price-box">
                                    {% if product.sale_price > 0 %}
                                        <p class="original-price" style="font-size: 0.6em; text-decoration: line-through; color: rgb(171, 171, 171);">
                                            R{{ product.price }}
                                        </p>
                                        <p class="sale-price" style="font-size: 1em; font-weight: 600; transform: translateY(-40%);">
                                            R{{ product.sale_price }}
                                        </p>
                                    {% else %}
                                        <p class="original-price" style="font-weight: 500;">
                                            R{{ product.price }}
                                        </p>
                                    {% endif %}
                                </div>
                            </div>
                            {% if product.get_stock_status_display != "Out of stock" %}
                                <form method="POST" action="{% url 'main:add_to_cart' product.pk %}">
                                    {% csrf_token %}
                                    <input type="submit" value="Add To Cart" class="btn-add-to-cart" id="btn-add-to-cart-{{ product.pk }}">
                                </form>
                            {% endif %}
                        </li>
                    {% endif %}
                {% endfor %}   
            </ul>
        </div>
    </div>
{% endfor %}
{% endblock %}

main/templates/login.html
{% extends "home.html" %}
{% block content %}
<style>
    .wrapper{
        position: relative;
        width: 400px;
        height: 440px;
        background: transparent;
        border: 2px solid rgba(255, 255, 255, 0.5);
        border-radius: 5px;
        backdrop-filter: blur(5px);
        display: flex;
        justify-content: center;
        align-items: center;
        overflow: hidden;
        transition: height .2s ease;
        margin-left: 40%;
    }

    .wrapper.active{
        height: 520px;
    }

    .wrapper .form-box{
        width: 100%;
        padding: 40px;
    }

    .wrapper .form-box.login{
       transition: transform .18s ease;
       transform: translateX(0)
    }

    .wrapper.active .form-box.login{
        transition: none;
        transform: translateX(-400px)
    }

    .wrapper .form-box.register{
        position: absolute;
        transition: none;
        transform: translateX(400px);
    }

    .wrapper.active .form-box.register{
        transition: transform .18s ease;
        transform: translateX(0)
    }

    .form-box h1{
        font-size: 2em;
        font-weight: 600;
        color: rgb(61, 61, 61);
        text-align: center;
    }

    .input-box{
        position: relative;
        width: 100%;
        height: 50px;
        border-bottom: 2px solid gray;
        margin: 30px 0;
    }

    .input-box label{
        position: absolute;
        top: 50%;
        left: 1px;
        transform: translateY(-55%);
        font-size: 1em;
        font-weight: 700;
        color: rgb(61, 61, 61);
        pointer-events: none;
        transition: .3s;
    }

    .input-box input:focus~label,
    .input-box input:valid~label{
        top: -5px;
    }

    .input-box input{
        width: 100%;
        height: 100%;
        background: transparent;
        border: none;
        outline: none;
        color: rgb(61, 61, 61);
        font-weight: 600;
        padding: 0 35px 0 5px;
    }

    input.btn{
        width: 100%;
        height: 45px;
        background-color: gainsboro;
        cursor: pointer;
        font-weight: 600;
    }

    .login-register{
        font-size: .9em;
        text-align: center;
        font-weight: 600;
        margin: 25px 0 10px;
        color: gainsboro;
    }

    .login-register p a {
        color: gainsboro;
        text-decoration: none;
        font-weight: 700;
    }

    .login-register p a:hover{
        text-decoration: underline;
    }
</style>
{% if error_message %}
    <div class="alert alert-danger" role="alert">
        {{ error_message }}
    </div>
{% endif %}
<div class="wrapper">
    <div class="form-box login">
        <h1>Login</h1>
        <form action="{% url 'main:attempt_login' %}" method="post">
            {% csrf_token %}
            <div class="input-box">
                <input type="text" name="username" required>
                <label>Username</label>
            </div>
            <div class="input-box">
                <input type="password" name="password" required>
                <label>Password</label>
            </div>
            <input type="submit" class="btn" value="Login">
            <div class="login-register">
                <p>Don't have an account? <a href=# class="register-link">Register</a></p>
            </div>
        </form>
    </div>
    <div class="form-box register">
        <h1>Register</h1>
        <form action="{% url 'main:create_account' %}" method="post">
            {% csrf_token %}
            <div class="input-box">
                <input type="text" name="firstname" required>
                <label>First Name</label>
            </div>
            <div class="input-box">
                <input type="text" name="username" required>
                <label>Username</label>
            </div>
            <div class="input-box">
                <input type="password" name="password" required>
                <label>Password</label>
            </div>
            <input type="submit" class="btn" value="Register">
            <div class="login-register">
                <p>Already have an account? <a href=# class="login-link">Login</a></p>
            </div>
        </form>
    </div>
</div>
<script>
    const wrapper = document.querySelector('.wrapper')
    const loginLink = document.querySelector('.login-link')
    const registerLink = document.querySelector('.register-link')

    registerLink.addEventListener('click', () =>{
        wrapper.classList.add('active')
    })

    loginLink.addEventListener('click', ()=>{
        wrapper.classList.remove('active')
    })
</script>
{% endblock %}